import Head from 'next/head'
import { useEffect, useState } from 'react'
import { ethers } from 'ethers'
import styles from '../styles/Home.module.css'
import { connectToTokenContract, connectToPoolContract, getAccount, getProviderSigned, getProviderSigned_pool } from '../utils/ethers'
import Token from '../artifacts/contracts/Token.sol/Token.json';
import Poolzi from '../artifacts/contracts/Poolzi.sol/Poolzi.json';



export default function Home() {

  const [contract, setContract] = useState();
  const [supply, setSupply] = useState();
  const [balance, setBalance] = useState();

  const [bet1, setBet1] = useState(0);
  const [bet2, setBet2] = useState(0);

  useEffect(async () => {
    const contract = await connectToTokenContract();
    setContract(contract);
    _getSupply(contract);
    _getBalance(contract);
  }, []);
  
  async function _getSupply(contract) {
    const totalSupply = await contract.totalSupply();
    setSupply(ethers.utils.formatUnits(totalSupply, 0));
  } 
  
  async function _getBalance(contract) {
    const account = await getAccount();
    const balanceOfUser = await contract.balanceOf(account);
    setBalance(ethers.utils.formatUnits(balanceOfUser, 0));
  }

  async function _transfer() {
    const contract = await getProviderSigned();
    const transaction = await contract.transfer(
      '0x4bD23e98d0D492536F2e84630aDEbE2Fd01AFBc2', 
      "2500"
    );
    await transaction.wait();
  }

  // Navi : #3874
  async function _placeBet() {
    if (bet1) {
      const contract = await getProviderSigned_pool();
      console.log("CONTRACT", contract);
      const placeBet = await contract.placeBets(1, 3874, bet1);
      console.log("placeBet", placeBet);
    }
  }
  console.log(bet1, bet2);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Bubble Token!</a>
        </h1>
        <p>Supply is : {supply}</p>
        <p>My balance is : {balance} </p>
        <div className='flex'>
          <div className='card'>
            <div class="mb-4">
              <label class="block text-gray-700 text-sm font-bold mb-2" for="bet1">
                Team 1
              </label>
              <input onChange={e => setBet1(e.target.value)} class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="bet1" type="number" placeholder="0"/>
            </div>
          </div>
          <div className='card'>
            <div class="mb-4">
              <label class="block text-gray-700 text-sm font-bold mb-2" for="bet2">
                Team 2
              </label>
              <input onChange={e => setBet2(e.target.value)} class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="bet2" type="number" placeholder="0"/>
            </div>
          </div>
        </div>
        <div className='mt-5'>
          <button onClick={() => _placeBet()} className='bg-green-500 hover:bg-pink-600 text-white font-bold py-2 px-4 rounded-full m-auto'>Bet</button>
          <button onClick={() => _transfer()} className='bg-green-500 hover:bg-pink-600 text-white font-bold py-2 px-4 rounded-full m-auto'>Transfer</button>
        </div>
      </main>
    </div>
  )
}
